apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-bitrix_bacup_mysql
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  chedule: "0-59/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:          
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
          