apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-bitrix-mysql
spec:
  schedule: "0-59/1 * * * *"
  #schedule: "30 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - dd=$(date +'%F_%H-%M-%S') \
              && echo $dd \
              && ls -l /nfs-data \
            volumeMounts:
            - mountPath: /nfs-data
              name: test-volume
          volumes:
          - name: test-volume
            nfs:
              server: 10.57.0.77
              path: /home/KVM_1/backup/nfs_2
              readOnly: false
          restartPolicy: OnFailure