apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-bitrix-api-code
spec:
  #schedule: "0-59/15 * * * *"
  schedule: "30 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |
              ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && 
              dd=$(date +'%F_%H-%M-%S') && 
              echo $dd &&                             
              kubectl cp site/bitrix-app-app-557599fbd7-zlfg5:/app/api/ /nfs-data/it-api-code_daily/$dd -c bitrix-app &&                             
              ls -l /nfs-data/it-api-code_daily/$dd 
            volumeMounts:
            - mountPath: /nfs-data
              name: test-volume
          volumes:
          - name: test-volume
            nfs:
              server: 10.57.0.15
              path: /home/Backup_DISK1/backup_kenguru.ru
              readOnly: false
          restartPolicy: OnFailure
          backoffLimit: 3
