apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-cluster-nodesverify
spec:
  ###schedule: "0-59/15 * * * *"
  schedule: "40 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |
              ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && 
              dd=$(date +'%F_%H-%M-%S') &&               
              echo $dd &&                             
              count_nodes=$(kubectl get nodes  | grep " Ready" | wc -l) &&               
              find /nfs-data/cluster_nodesverify* -mtime +10 -delete ; 
              echo $dd - $count_nodes >> $dd.txt
              ls -l /nfs-data/cluster_nodesverify/
            volumeMounts:
            - mountPath: /nfs-data
              name: test-volume
          volumes:
          - name: test-volume
            nfs:
              server: 10.57.0.150
              path: /home/Backup_DISK1/backup_kenguru.ru
              readOnly: false
          restartPolicy: OnFailure
          backoffLimit: 3