apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-backup-bitrix-mysql
spec:
  schedule: "0-59/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure