apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-bitrix-mysql-log
spec:
  #schedule: "0-59/15 * * * *"
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |              
              dd=$(date +'%F_%H-%M-%S') && 
              echo $dd &&               
              kubectl -n site exec --stdin --tty site-bitrix-app-mysql-0 -- /bin/bash -c  '$dd >> /tmp/t.log' && 
              kubectl -n site exec --stdin --tty site-bitrix-app-mysql-0 -- /bin/bash -c  'mysql -u"root" -p"HJu15f713fqb7cdivHgnNktOrXWWraq1" -e "SELECT DB,USER,HOST,STATE FROM INFORMATION_SCHEMA.PROCESSLIST ORDER BY DB DESC;" >> /tmp/t.log' && 
              kubectl cp site/site-bitrix-app-mysql-0:/tmp/t.log /nfs-data/t.log &&                        
              ls -l /nfs-data 
            volumeMounts:
            - mountPath: /nfs-data
              name: test-volume
          volumes:
          - name: test-volume
            nfs:
              server: 10.58.0.14
              path: /home/Backup/backup_kenguru.ru/bitrix_mysql_log

              readOnly: false
          restartPolicy: OnFailure
          backoffLimit: 3
