apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-bitrix-api-code
spec:
  #schedule: "0-59/15 * * * *"
  schedule: "30 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |
              ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && 
              dd=$(date +'%F_%H-%M-%S') && 
              echo $dd && 
              # kubectl -n site exec --stdin --tty site-bitrix-app-mysql-0 -- /bin/bash -c  'rm /tmp/bitrix*' &&
              # kubectl -n site exec --stdin --tty site-bitrix-app-mysql-0 -- /bin/bash -c  'mysqldump  -u root --password=HJu15f713fqb7cdivHgnNktOrXWWraq1 --routines bitrix-app > /tmp/bitrix_mysql_'$dd'.sql' && 
              kubectl cp site/site-bitrix-app-mysql-0:/ /app/api* /nfs-data/it-api-code && 
              # kubectl -n site exec --stdin --tty site-bitrix-app-mysql-0 -- /bin/bash -c  'rm /tmp/bitrix*' && 
              #find /nfs-data* -mtime +10 -delete && 
              ls -l /nfs-data/it-api-code 
            volumeMounts:
            - mountPath: /nfs-data
              name: test-volume
          volumes:
          - name: test-volume
            nfs:
              server: 10.57.0.15
              path: /home/Backup_DISK1/backup_kenguru.ru/bitrix_mysql
              readOnly: false
          restartPolicy: OnFailure
          backoffLimit: 3
