apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-gitlab-postgreesql-daily
spec:
  #schedule: "0-59/15 * * * *"
  schedule: "35 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy:  {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |
              ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && 
              dd=$(date +'%F_%H-%M-%S') && 
              echo $dd && 
              kubectl -n gitlab exec --stdin --tty   gitlab-postgresql-0 -- /bin/bash -c  'rm /tmp/gitlab* ' ;              
              kubectl -n gitlab exec --stdin --tty   gitlab-postgresql-0 -- /bin/bash -c  'echo 12345678' ;
              kubectl -n gitlab exec --stdin --tty   gitlab-postgresql-0 -- /bin/bash -c  ' pg_dump -w "postgresql://postgres:S1DhQVs81SoBCNgjnApcg7IQFt7uc6JOAFPSZpzROE0UQ5EqV3B1eohkF7mIKvpt@gitlab-postgresql-hl.gitlab.svc.cluster.local:5432/gitlabhq_production" > /tmp/gitlab_postgreessql_'$dd'.sql' && 
              kubectl cp gitlab/gitlab-postgresql-0:/tmp/gitlab_postgreessql_$dd.sql /nfs-data/gitlab_postgreessql_$dd.sql &&                             
              kubectl -n gitlab exec --stdin --tty   gitlab-postgresql-0 -- /bin/bash -c  'rm /tmp/gitlab* ' ;              
              find /nfs-data* -mtime +10 -delete ; 
              ls -l /nfs-data 
            volumeMounts:
            - mountPath: /nfs-data
              name: test-volume
          volumes:
          - name: test-volume
            nfs:
              server: 10.57.0.15
              path: /home/Backup_DISK1/backup_kenguru.ru/gitlab_postgreesql_daily
              readOnly: false
          restartPolicy: OnFailure
          backoffLimit: 3
